'\" t
.\"     Title: amadmin
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMADMIN" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amadmin \- administrative interface to control Amanda backups
.SH "SYNOPSIS"
.HP \w'\fBamadmin\fR\ 'u
\fBamadmin\fR [\fB\-o\fR\ \fIconfigoption\fR...] \fIconfig\fR \fIcommand\fR [\fIcommand_options\fR...]
.SH "DESCRIPTION"
.PP
\fBAmadmin\fR
performs various administrative tasks on the
\fIconfig\fR
Amanda configuration\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about Amanda\&.
.SH "COMMANDS"
.PP
Commands that take a
\fIhostname\fR
[
\fIdisks\fR
] parameter pair operate on all disks in the
\fBdisklist\fR(5)
for that
\fIhostname\fR
if no disks are specified\&. Where
\fIhostname\fR
is also marked as being optional, the command operates on all hosts and disks in the
\fBdisklist\fR(5)
when no hostname is given\&. Both
\fIhostname\fR
and
\fIdisks\fR
are match expressions; see
\fBamanda-match\fR(7)
for a description\&.
.PP
\fBversion\fR
.RS 4
Show the current version and some compile time and runtime parameters\&. The
\fIconfig\fR
parameter must be present but is ignored\&.
.RE
.PP
\fBestimate\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Print the server estimate for the dles, each output lines have the following format:
.nf
  hostname diskname level size
.fi
.PP
hostname
.RS 4
The quoted hostname
.RE
.PP
diskname
.RS 4
The quoted diskname
.RE
.PP
level
.RS 4
The level of the estimate
.RE
.PP
size
.RS 4
The estimate size in kbytes
.RE
.RE
.PP
\fBforce\-bump\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Force the
\fIdisks\fR
on
\fIhostname\fR
to bump to a new incremental level during the next Amanda run\&.
.RE
.PP
\fBforce\-no\-bump\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Force the
\fIdisks\fR
on
\fIhostname\fR
to not bump to a new incremental level during the next Amanda run\&.
.RE
.PP
\fBunforce\-bump\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Undo a previous
\fBforce\-bump\fR
or
\fBforce\-no\-bump\fR
command\&.
.RE
.PP
\fBforce\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Force the
\fIdisks\fR
on
\fIhostname\fR
to do a full (level 0) backup during the next Amanda run\&.
.RE
.PP
\fBunforce\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Undo a previous
\fBforce\fR
command\&.
.RE
.PP
\fBreuse\fR \fItapelabel\fR [ \&.\&.\&. ]
.RS 4
The tapes listed will be available for reuse at their point in the tape cycle\&.
.RE
.PP
\fBno\-reuse\fR \fItapelabel\fR [ \&.\&.\&. ]
.RS 4
The tapes listed will not be reused when their turn comes up again in the tape cycle\&. Note that if this causes the number of reusable tapes to drop below the
\fBamanda\&.conf\fR
\fItapecycle\fR
value, Amanda will request new tapes until the count is satisfied again\&.
.sp
Tape marked
\fIno\-reuse\fR
are available for recovery, marking them
\fIno\-reuse\fR
is a security to be sure amanda will not overwrite them\&.
.RE
.PP
\fBdue\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Show when the next full dump is due\&.
.RE
.PP
\fBfind\fR [ \fB\-\-sort\fR \fIhkdlpbfw\fR ] [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Display all backups currently on tape or in the holding disk\&. The tape label or holding disk filename, file number, and status are displayed\&.
.sp
The
\fB\-\-sort\fR
option changes the sort order using the following flags:
.sp
.nf
\fIh\fR: host name
\fIk\fR: disk name
\fId\fR: dump timestamp
\fIl\fR: backup level
\fIp\fR: dump part
\fIb\fR: tape label
\fIf\fR: filenum on tape
\fIw\fR: write timestamp
.fi
.sp
An uppercase letter reverses the sort order for that key\&. The default sort order is
\fBhkdlpbfw\fR\&.
.RE
.PP
\fBholding delete\fR \fIhostname\fR [ \fIdisk\fR [ \fIdatestamp\fR [ \&.\&. ] ] ]
.RS 4
Delete holding files matching the given specification\&. At least a hostname must be provided\&.
.RE
.PP
\fBholding list\fR [\-l] [\-d] [ \fIhostname\fR [ \fIdisk\fR [ \fIdatestamp\fR [ \&.\&. ] ] ] ]
.RS 4
List holding files matching the given dump specification, or all holding files if no specification is provided\&. See
\fBamanda-match\fR(7)
for more information on dump specifications\&. With \*(Aq\-l\*(Aq, additional information (size, level, and whether the dump is outdated) is provided\&. With \*(Aq\-d\*(Aq, only outdated dumps are shown\&.
.sp
An outdated holding file is one which is not required for a restore of the
\fImost recent\fR
dump\&. Note that outdated dumps may still be required for restores at earlier dates\&. For example, assume that a DLE had a level 0 on Monday, level 1\*(Aqs Tuesday through Thursday, and a level 2 on Friday\&. Then the files required for a restore of Fridays (the most recent) dump are those from Monday (level 0), Thursday (level 1), and Friday (level 2)\&. Tuesday and Wednesday\*(Aqs files are outdated\&.
.RE
.PP
\fBdelete\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]+
.RS 4
Delete the specified
\fIdisks\fR
on
\fIhostname\fR
from the Amanda database\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
If you do not also remove the disk from the
\fBdisklist\fR(5)
file, Amanda will treat it as a new disk during the next run\&.
.sp .5v
.RE
.RE
.PP
\fBtape\fR
.RS 4
Display the tape(s) Amanda expects to write to during the next run\&. See also
\fBamcheck\fR(8)\&.
.RE
.PP
\fBbumpsize\fR
.RS 4
Display the current bump threshold parameters, calculated for all backup levels\&.
.RE
.PP
\fBbalance\fR [ \fB\-\-days\fR \fI<num>\fR ]
.RS 4
Display the distribution of full backups throughout the dump schedule\&.
.RE
.PP
\fBexport\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Convert records from the Amanda database to a text format that may be transmitted to another Amanda machine and
\fBimport\fRed\&.
.RE
.PP
\fBimport\fR
.RS 4
Convert
\fBexport\fRed records read from standard input to a form Amanda uses and insert them into the database on this machine\&.
.RE
.PP
\fBdisklist\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Display the
\fBdisklist\fR(5)
information for each of the
\fIdisks\fR
on
\fIhostname\fR
(or all hosts)\&. Mostly used for debugging\&.
.RE
.PP
\fBhosts\fR
.RS 4
Output a list of distinct hosts in the
\fBdisklist\fR(5), one per line, for easy use in shell scripts\&.
.RE
.PP
\fBdles\fR
.RS 4
Output a list of distinct DLEs in the
\fBdisklist\fR(5), one per line with host and diskname separated by a space, for easy use in shell scripts\&.
.RE
.PP
\fBinfo\fR [ \fIhostname\fR [ \fIdisks\fR ]* ]*
.RS 4
Display the database record for each of the
\fIdisks\fR
on
\fIhostname\fR
(or all hosts)\&. Mostly used for debugging\&.
.RE
.PP
\fB\-o \fR\fB\fIconfigoption\fR\fR
.RS 4
See the "CONFIGURATION OVERRIDE" section in
\fBamanda\fR(8)\&.
.RE
.SH "EXAMPLES"
.PP
Request three specific file systems on
\fImachine\-a\fR
get a full level 0 backup during the next Amanda run\&.
.nf
$ amadmin daily force machine\-a / /var /usr
amadmin: machine\-a:/ is set to a forced level 0 tonight\&.
amadmin: machine\-a:/var is set to a forced level 0 tonight\&.
amadmin: machine\-a:/usr is set to a forced level 0 tonight\&.
.fi
.PP
Request all file systems on
\fImachine\-b\fR
get a full level 0 backup during the next Amanda run\&.
.nf
$ amadmin daily force machine\-b
amadmin: machine\-b:/ is set to a forced level 0 tonight\&.
amadmin: machine\-b:/var is set to a forced level 0 tonight\&.
amadmin: machine\-b:/usr is set to a forced level 0 tonight\&.
amadmin: machine\-b:/home is set to a forced level 0 tonight\&.
.fi
.PP
Undo the previous
\fBforce\fR
request for
/home
on
\fImachine\-b\fR\&. The other file systems will still get a full level 0 backup\&.
.nf
$ amadmin daily unforce machine\-b /home
amadmin: force command for machine\-b:/home cleared\&.
.fi
.PP
Locate backup images of
/var
from
\fImachine\-c\fR\&. The
\fItape or file\fR
column displays either a tape label or a filename depending on whether the image is on tape or is still in the holding disk\&. If the image is on tape, the
\fIfile\fR
column tells you which file on the tape has the image (file number zero is a tape label)\&. This column shows zero and is not meaningful if the image is still in the holding disk\&. The
\fIstatus\fR
column tells you whether the backup was successful or had some type of error\&.
.nf
$ amadmin daily find machine\-c /var
date        host      disk lv tape or file                 file part  status
2000\-11\-09  machine\-c /var  0 000110                       9   \-\-  OK
2000\-11\-08  machine\-c /var  2 000109                       2   \-\-  OK
2000\-11\-07  machine\-c /var  2 /amanda/20001107/machine\-c\&._var\&.2  0 OK
2000\-11\-06  machine\-c /var  2 000107                       2   \-\-  OK
2000\-11\-05  machine\-c /var  2 000106                       3   \-\-  OK
2000\-11\-04  machine\-c /var  2 000105                       2   \-\-  OK
2000\-11\-03  machine\-c /var  2 000104                       2   \-\-  OK
2000\-11\-02  machine\-c /var  2 000103                       2   \-\-  OK
2000\-11\-01  machine\-c /var  1 000102                       5   \-\-  OK
2000\-10\-31  machine\-c /var  1 000101                       3   \-\-  OK
.fi
.PP
Forget about the
/workspace
disk on
\fImachine\-d\fR\&. If you do not also remove the disk from the
\fBdisklist\fR(5)
file, Amanda will treat it as a new disk during the next run\&.
.nf
$ amadmin daily delete machine\-d /workspace
amadmin: machine\-d:/workspace deleted from database\&.
amadmin: NOTE: you\*(Aqll have to remove these from the \fBdisklist\fR(5) yourself\&.
.fi
.PP
Find the next tape Amanda will use (in this case,
123456)\&.
.nf
$ amadmin daily tape
The next Amanda run should go onto tape 123456 or a new tape\&.
.fi
.PP
Show how well full backups are balanced across the dump cycle\&. The
\fIdue\-date\fR
column is the day the backups are due for a full backup\&.
\fI#fs\fR
shows the number of filesystems doing full backups that night, and
\fIorig KB\fR
and
\fIout KB\fR
show the estimated total size of the backups before and after any compression, respectively\&.
.PP
The
\fIbalance\fR
column shows how far off that night\*(Aqs backups are from the average size (shown at the bottom of the balance column)\&. Amanda tries to keep the backups within +/\- 5%, but since the amount of data on each filesystem is always changing, and Amanda will never delay backups just to rebalance the schedule, it is common for the schedule to fluctuate by larger percentages\&. In particular, in the case of a tape or backup failure, a bump will occur the following night, which will not be smoothed out until the next pass through the schedule\&.
.PP
The last line also shows an estimate of how many Amanda runs will be made between full backups for a file system\&. In the example, a file system will probably have a full backup done every eight times Amanda is run (e\&.g\&. every eight days)\&.
.nf
$ amadmin daily balance
 due\-date  #fs   orig KB    out KB  balance
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
11/10 Mon   21    930389    768753    +5\&.1%
11/11 Tue   29   1236272    733211    +0\&.2%
11/12 Wed   31   1552381    735796    +0\&.6%
11/13 Thu   23   1368447    684552    \-6\&.4%
11/14 Fri   32   1065603    758155    +3\&.6%
11/15 Sat   14   1300535    738430    +0\&.9%
11/16 Sun   31   1362696    740365    +1\&.2%
11/17 Mon   30   1427936    773397    +5\&.7%
11/18 Tue   11   1059191    721786    \-1\&.3%
11/19 Wed   19   1108737    661867    \-9\&.5%
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
TOTAL      241  12412187   7316312   731631  (estimated 8 runs per dumpcycle)
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda\fR(8),
\fBamcheck\fR(8),
\fBamdump\fR(8),
\fBamrestore\fR(8),
\fBamfetchdump\fR(8),
\fBamanda-match\fR(7)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
