'\" t
.\"     Title: amcheckdump
.\"    Author: Ian Turner <ian@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMCHECKDUMP" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amcheckdump \- check the results of an Amanda dump
.SH "SYNOPSIS"
.HP \w'\fBamcheckdump\fR\ 'u
\fBamcheckdump\fR [\-\-timestamp|\-t\ \fItimestamp\fR] [\-\-verbose] [\fB\-o\fR\ \fIconfigoption\fR...] \fIconfig\fR
.SH "DESCRIPTION"
.PP
\fBAmcheckdump\fR
verifies Amanda dump images by reading them from storage volume(s) and verifying that the images can be parsed by the appropriate application (if available)\&. For example, a GNUTAR image is passed to GNU Tar for parsing, and any errors (e\&.g\&., corrupt or missing data) are noted\&.
.PP
The application runs on the most recent dump or, if
\fI\-\-timestamp\fR
is specified, on the most recent dump with that timestamp\&. Note that the verification is local to the Amanda server; if the dump application is not available, or is configured differently on the server than on the client, then the verification will most likely fail\&.
.PP
If a changer is available, it is used to load the required tapes\&. Otherwise, the application interactively requests the tapes\&.
.PP
See the "\fBCONFIGURATION OVERRIDE\fR" section in
\fBamanda\fR(8)
for information on the
\-o
option\&.
.SH "EXAMPLE"
.PP
.nf
# check the most recent dump
amcheckdump MYCONFIG

# check a specific dump from back in \*(Aq78
amcheckdump MYCONFIG \-\-timestamp 19780615
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamcheck\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBIan Turner\fR <\&ian@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
