'\" t
.\"     Title: amcleanup
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMCLEANUP" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amcleanup \- run the Amanda cleanup process after a failure
.SH "SYNOPSIS"
.HP \w'\fBamcleanup\fR\ 'u
\fBamcleanup\fR [\fB\-k\fR] [\fB\-p\fR] [\fB\-r\fR] [\fB\-v\fR] \fIconfig\fR
.SH "DESCRIPTION"
.PP
\fBAmcleanup\fR
generates the
\fIAmanda Mail Report\fR
and updates the Amanda databases after a system failure on a tape server host\&. This cleanup process is normally done automatically as part of the
\fBamdump\fR
program, but if
\fBamdump\fR
cannot complete for some reason (usually because of a tape server host crash),
\fBamcleanup\fR
must be run some time later (usually during system boot)\&.
.PP
The
\fBamcleanupdisk\fR
program is run with the same
[\fB\-r\fR]
and
[\fB\-v\fR]
options\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about Amanda\&.
.SH "OPTIONS"
.PP
\fB\-k\fR
.RS 4
Kill all process listed in the log file are their child\&. if there is no log file, then kill all amdump and amflush process and their child\&.
.RE
.PP
\fB\-p\fR
.RS 4
Do the cleanup only if all process listed in the log file are already terminated\&.
.RE
.PP
\fB\-r\fR
.RS 4
Remove bad file in holding disk\&. This options is passed to amcleanupdisk\&.
.RE
.PP
\fB\-v\fR
.RS 4
Generate verbose output\&. This options is passed to amcleanupdisk\&.
.RE
.SH "EXAMPLES"
.PP
This example runs the Amanda cleanup process by hand after a failure\&.
.nf
% amcleanup daily
.fi
.PP
Putting the following line in a system boot script (e\&.g\&.
/etc/rc\&.local) runs the Amanda cleanup process as part of the reboot, eliminating the need to run it by hand\&.
.nf
/usr/local/sbin/amcleanup daily
.fi
.PP
If nothing needs to be done,
\fBamcleanup\fR
exits normally with the message:
.nf
amcleanup: no unprocessed logfile to clean up\&.
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamdump\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
