'\" t
.\"     Title: amcrypt-ossl
.\"    Author: Kevin Till <kevin.till@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMCRYPT\-OSSL" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amcrypt-ossl \- crypt program for Amanda symmetric data encryption using OpenSSL
.SH "SYNOPSIS"
.HP \w'\fBamcrypt\-ossl\fR\ 'u
\fBamcrypt\-ossl\fR [\-d]
.SH "DESCRIPTION"
.PP

\fBamcrypt\-ossl\fR
uses
\fBOpenSSL\fR
to encrypt and decrypt data\&. OpenSSL is available from
www\&.openssl\&.org\&. OpenSSL offers a wide variety of cipher choices (
\fBamcrypt\-ossl\fR
defaults to 256\-bit AES) and can use hardware cryptographic accelerators on several platforms\&.
.PP

\fBamcrypt\-ossl\fR
will search for the OpenSSL program in the following directories: /bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin\&.
.SH "PASSPHRASE MANAGEMENT"
.PP

\fBamcrypt\-ossl\fR
uses the same pass phrase to encrypt and decrypt data\&. It is very important to store and protect the pass phrase properly\&. Encrypted backup data can
\fBonly\fR
be recovered with the correct passphrase\&.
.PP
OpenSSL\*(Aqs key derivation routines use a salt to guard against dictionary attacks on the pass phrase; still it is important to pick a pass phrase that is hard to guess\&. The Diceware method (see
www\&.diceware\&.com) can be used to create passphrases that are difficult to guess and easy to remember\&.
.SH "FILES"
.PP
/var/lib/amanda/\&.am_passphrase
.RS 4
File containing the pass phrase\&. It should not be readable by any user other than the Amanda user\&.
.RE
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBopenssl\fR(1),
\fBamcrypt-ossl-asym\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBKevin Till\fR <\&kevin\&.till@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
.SH "NOTES"
.IP " 1." 4
www.openssl.org
.RS 4
\%http://www.openssl.org/
.RE
.IP " 2." 4
www.diceware.com
.RS 4
\%http://www.diceware.com/
.RE
