'\" t
.\"     Title: amdump
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMDUMP" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amdump \- back up all disks in an Amanda configuration
.SH "SYNOPSIS"
.HP \w'\fBamdump\fR\ 'u
\fBamdump\fR [\fB\-\-no\-taper\fR] [\fB\-o\fR\ \fIconfigoption\fR...] \fIconfig\fR [\fIhost\fR\ [\fIdisk\fR...]...]
.SH "DESCRIPTION"
.PP
\fBAmdump\fR
is the main interface to the Amanda backup process\&. It loads the specified configuration and attempts to back up every disk specified by the
\fBdisklist\fR(5)\&.
\fBAmdump\fR
is normally run by
\fBcron\fR\&.
.PP
The command optionally takes a set of DLE specifications (see
\fBamanda-match\fR(7)) to narrow the DLEs that will be dumped\&. All disks are dumped if no expressions are given\&.
.PP
If a file named
hold
exists in the configuration directory,
\fBamdump\fR
will wait until it is removed before starting the backups\&. This allows scheduled backups to be delayed when circumstances warrant, for example, if the tape device is being used for some other purpose\&. While waiting,
\fBamdump\fR
checks for the hold file every minute\&.
.PP
In some cases it is desirable to dump all Amanda clients to holding disk without writing anything to storage media\&. The
\fB\-\-no\-taper\fR
option instructs Amanda to not start the taper, and thus enter degraded mode immediately\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about Amanda\&.
.SH "OPTIONS"
.PP
\fIhost\fR [\fIdisk\fR]*
.RS 4
Specify the host and disk on which the command will work \-\- see the description of DLE specifications in
\fBamanda-match\fR(7)\&.
.RE
.PP
\fB\-o \fR\fB\fIconfigoption\fR\fR
.RS 4
See the "CONFIGURATION OVERRIDE" section in
\fBamanda\fR(8)\&.
.RE
.SH "EXAMPLE"
.PP
Here is a typical crontab entry\&. It runs
\fBamdump\fR
every weeknight at 1 a\&.m\&. as user
\fBbin\fR:
.nf
0 1 * * 1\-5 bin /usr/local/sbin/amdump daily
.fi
.PP
Please see the
\fBcrontab\fR(5)
or
\fBcrontab\fR(1)
manual page for the correct crontab format for your system\&.
.SH "MESSAGES"
.PP
amdump: waiting for hold file to be removed
.RS 4
The "hold" file exists and
\fBamdump\fR
is waiting for it to be removed before starting backups\&.
.RE
.PP
amdump: amdump or amflush is already running, or you must run amcleanup
.RS 4
Amdump detected another
\fBamdump\fR
or
\fBamflush\fR
running, or the remains of a previous incomplete
\fBamdump\fR
or
\fBamflush\fR
run\&. This run is terminated\&. If the problem is caused by the remains of a previous run, you must execute
\fBamcleanup\fR(8)
and then rerun
\fBamdump\fR\&.
.RE
.SH "EXIT CODE"

The exit code of \fBamdump\fR is the ORed value of:
.nf
 0  = success
 1  = error
 2  = a dle give strange message
 4  = a dle failed
 8  = Don\*(Aqt know the status of a dle (RESULT_MISSING in the report)
 16 = tape error or no more tape
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamcheck\fR(8),
\fBamcleanup\fR(8),
\fBamrestore\fR(8),
\fBamflush\fR(8),
\fBcron\fR(8),
\fBamanda-match\fR(7)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
