'\" t
.\"     Title: amgtar
.\"    Author: Jean-Louis Martineau <martineau@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMGTAR" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amgtar \- Amanda Application to interface with GNU Tar
.SH "DESCRIPTION"
.PP
Amgtar is an Amanda Application API script\&. It should not be run by users directly\&. It uses GNU Tar to backup and restore data\&.
.PP
The
\fBdiskdevice\fR
in the disklist (DLE) must be the directory to backup\&.
.SH "PROPERTIES"
.PP
This section lists the properties that control amgtar\*(Aqs functionality\&. See
\fBamanda-applications\fR(7)
for information on application properties and how they are configured\&.
.PP
ATIME\-PRESERVE
.RS 4

If "YES" (the default), amgtar use the \fI\-\-atime\-preserve=system\fR option of gnutar to not update the atime of all files accessed; if "NO", gnutar will updates the atime for all files accessed\&. This property works only if you have gnutar 1\&.15\&.90 or newer, if not, you must set ATIME_PRESERVE to "NO"\&.
.RE
.PP
CHECK\-DEVICE
.RS 4

If "YES" (the default), amgtar checks that the device number doesn\*(Aqt change for each file\&. If "NO", changes in device number are ignored\&.  To ignore device numbers, tar must support the \fI\-\-no\-check\-device\fR option (gnutar 1\&.19\&.90 and newer)\&. This option is needed for some filesystems and devices on which device numbers change frequently, such as LVM or FiberChannel\&.
.RE
.PP
COMMAND\-OPTIONS
.RS 4
If set, theses options are passed asis to gtar\&. Each option must be a different value of the property\&. Some option can break how amanda do backup, use it with care\&.

Use:
.nf
  property "COMMAND\-OPTIONS" "\-\-foo" "bar"
.fi

Do not use:
.nf
  property "COMMAND\-OPTIONS" "\-\-foo bar"
.fi
.RE
.PP
DIRECTORY
.RS 4

If set, gnutar will backup from that directory instead of the \fIdiskdevice\fR set by the DLE\&. On restore, the data is restore in that directory instead of the current working directory\&.
.RE
.PP
GNUTAR\-LISTDIR
.RS 4

The directory where gnutar stores the database it uses to generate incremental dumps\&.  The default is set when Amanda is built\&.
.RE
.PP
GNUTAR\-PATH
.RS 4

The path to the gnutar binary\&.  The default is set when Amanda is built\&.
.RE
.PP
INCLUDE\-LIST\-GLOB
.RS 4

A filename containing include glob expression for the restore command\&.
.RE
.PP
EXCLUDE\-LIST\-GLOB
.RS 4

A filename containing exclude glob expression for the restore command\&.
.RE
.PP
ONE\-FILE\-SYSTEM
.RS 4

If "YES" (the default), do not allow gnutar to cross filesystem boundaries\&. If "NO", gnutar will cross filesystem boundaries\&.  This corresponds to the \fI\-\-one\-filesystem\fR option of gnutar\&.
.RE
.PP
TAR\-BLOCKSIZE
.RS 4

Block size of Nx512 bytes (default N=20)\&.  This corresponds to the \fI\-\-blocking\-factor\fR option of gnutar\&.
.RE
.PP
SPARSE
.RS 4

If "YES" (the default), gnutar will store sparse files efficiently\&. If "NO", then the \fI\-\-sparse\fR option is not given to gnutar, and it will not try to detect sparse files\&.
.RE
.PP
NO\-UNQUOTE
.RS 4

If "NO" (the default), gnutar doesn\*(Aqt get the \fI\-\-no\-unquote\fR option and the diskname can\*(Aqt have some characters, eg\&. \*(Aq\e\*(Aq\&. If "YES", then the \fI\-\-no\-unquote\fR option is given to gnutar and the diskname can have any characters\&.  This option is available only if you are using tar\-1\&.16 or newer\&.
.RE
.PP
ACLS
.RS 4

Default "NO"\&. If "YES", gnutar will preserve ACL extended attributes\&. This corresponds to the \fI\-\-acls\fR gnutar option\&. Requires a GNU Tar with nonstandard extended attribute patches from the Fedora Project\&.
.RE
.PP
SELINUX
.RS 4

Default "NO"\&. If "YES", gnutar will preserve SELinux extended attributes on Linux\&. This corresponds to the \fI\-\-selinux\fR gnutar option\&. Requires a GNU Tar with nonstandard extended attribute patches from the Fedora Project\&. 
.RE
.PP
XATTRS
.RS 4

Default "NO"\&. If "YES", gnutar will preserve all extended attributes\&. This corresponds to the \fI\-\-xattrs\fR gnutar option\&. If enabled, this option also implies the ACLS and SELINUX properties, regardless of their settings, as they are implemented as extended attributes\&. Requires a GNU Tar with nonstandard extended attribute patches from the Fedora Project\&.
.RE
.PP
EXIT\-HANDLING
.RS 4

List which exit status of gtar are good or bad\&. eg\&. "1=GOOD 2=BAD", exit status of 1 will produce a good backup, exit status of 2 will give an error\&.
.RE
.PP
NORMAL
.RS 4

List all regex (POSIX Extended Regular Expression syntax) that are normal output from gtar\&. These output are in the "FAILED DUMP DETAILS" section of the email report if the dump result is STRANGE or FAILED\&. Default values:
.nf
  "^could not open conf file"
  "^Elapsed time:"
  "^Throughput"
  ": socket ignored$"
  ": File \&.* shrunk by [0\-9][0\-9]* bytes, padding with zeros"
  ": Cannot add file \&.*: No such file or directory$"
  ": Error exit delayed from previous errors"
.fi
To treat one of these default patterns differently, specify it explicitly in a different property\&.
.RE
.PP
IGNORE
.RS 4

List all regex (POSIX Extended Regular Expression syntax) that amanda ignore\&. These output are never in the email report\&. Default values:
.nf
  ": Directory is new$"
  ": Directory has been renamed"
.fi
To treat one of these default patterns differently, specify it explicitly in a different property\&.
.RE
.PP
STRANGE
.RS 4

List all regex (POSIX Extended Regular Expression syntax) that are strange output from gtar\&. All gtar output that doesn\*(Aqt match a normal or ignore regex are strange by default\&. The result of the dump is STRANGE if gtar produce a strange output\&. These output are in the "FAILED DUMP DETAILS" section of the email report\&.
.RE
.PP
VERBOSE
.RS 4

Default: "NO"\&. If "YES", amgtar print more verbose debugging message and can leave temporary files in AMANDA_TMPDIR\&.
.RE
.SH "INCLUDE AND EXCLUDE LISTS"
.PP
This application supplies exclude lists via the
\fBGNU\-tar\fR
\fB\-\-exclude\-from\fR
option\&. This option accepts normal shell\-style wildcard expressions, using
\fB*\fR
to match any number of characters and
\fB?\fR
to match a single character\&. Character classes are represented with
\fB[\&.\&.]\fR, which will match any of the characters in the brackets\&. Expressions can be "anchored" to the base directory of the DLE by prefixing them with "\&./"\&. Without this prefix, they will match at any directory level\&. Expressions that begin or end with a "/" will not match anything: to completely exclude a directory, do not include the trailing slash\&. Example expressions:
.sp
.nf
  \&./temp\-files           # exclude top\-level directory entirely
  \&./temp\-files/          # BAD: does nothing
  /temp\-files            # BAD: does nothing
  \&./temp\-files/*         # exclude directory contents; include directory
  temp\-files             # exclude anything named "temp\-files"
  generated\-*            # exclude anything beginning with "generated\-"
  *\&.iso                  # exclude ISO files
  proxy/local/cache      # exclude "cache" in dir "local" in "proxy"
.fi
.PP
Similarly, include expressions are supplied to
\fBGNU\-tar\fR\*(Aqs
\fB\-\-files\-from\fR
option\&. This option ordinarily does not accept any sort of wildcards, but amgtar "manually" applies glob pattern matching to include expressions with only one slash\&. The expressions must still begin with "\&./", so this effectively only allows expressions like "\&./[abc]*" or "\&./*\&.txt"\&.
.SH "EXAMPLE"
.PP

.sp
.nf
  define application\-tool app_amgtar {
    plugin "amgtar"

    property "ATIME\-PRESERVE" "NO"
    property "CHECK\-DEVICE" "YES"
    property "GNUTAR\-LISTDIR" "/path/to/listdir"
    property "GNUTAR\-PATH" "/bin/tar"
    property "ONE\-FILE\-SYSTEM" "YES"
    property "TAR\-BLOCKSIZE" "20"
    property "SPARSE" "YES"
    property "ACLS" "NO"
    property "SELINUX" "NO"
    property "XATTRS" "NO"
    property "EXIT\-HANDLING" "1=GOOD 2=BAD"
    # change a default NORMAL regex to a STRANGE regex\&.
    property "STRANGE" ": socket ignored$"
    # add three new IGNORE regex
    property "IGNORE" ": Directory is new$"
    property append "IGNORE" ": Directory has been renamed"
    property append "IGNORE" "file changed as we read it$"
  }
.fi
A dumptype using this application might look like:
.sp
.nf
  define dumptype amgtar_app_dtyp {
    global
    program "APPLICATION"
    application "app_amgtar"
  }
.fi
Note that the
\fIprogram\fR
parameter must be set to
\fI"APPLCIATION"\fR
to use the
\fIapplication\fR
parameter\&.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBtar\fR(1),
\fBamanda.conf\fR(5),
\fBamanda-applications\fR(7)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBJean\-Louis Martineau\fR <\&martineau@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
.PP
\fBDustin J\&. Mitchell\fR <\&dustin@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
