'\" t
.\"     Title: amlabel
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMLABEL" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amlabel \- label an Amanda tape
.SH "SYNOPSIS"
.HP \w'\fBamlabel\fR\ 'u
\fBamlabel\fR [\fB\-\-barcode\ \fR\fB\fIbarcode\fR\fR] [\fB\-\-meta\ \fR\fB\fImeta\-label\fR\fR] [\fB\-\-assign\fR] [\fB\-f\fR] [\fB\-\-version\fR] [\fB\-o\fR\ \fIconfigoption\fR...] \fIconfig\fR [\fIlabel\fR] [slot\ \fIslot\fR]
.SH "DESCRIPTION"
.PP
This command applies a label to an Amanda volume, erasing the volume in the process\&.
.PP
Amanda uses labels to identify volumes:
\fBamdump\fR(8)
and
\fBamflush\fR(8)
verify the label before writing to make sure the proper volume is loaded, and the recovery programs use the label to ensure they are reading the data they expect\&.
.PP
If no
[\fIslot\fR]
and no
[\fIbarcode\fR]
is given, then
\fBamlabel\fR
labels the tape in the current slot of the default changer\&. If a slot is given, it labels the volume in that slot\&. If a barcode is given, it labels the volume with that barcode\&.
\fILabel\fR
may be any string that does not contain whitespace and that matches the
\fBlabelstr\fR
(see
\fBamanda.conf\fR(5))\&.
.PP
If
[\fIlabel\fR]
is not given, an autolabel is generated, see
\fBautolabel\fR
in
\fBamanda.conf\fR(5)\&.
.PP
If
[\fB\-\-assign\fR]
is given, the barcode and meta\-label are assigned to the label without labeling the volume\&. The label must already be in the tapelist file\&.
.PP
This command also appends the new volume to the
\fBtapelist\fR(5)
file, so that they will be used in the order they are labeled (depending on the taperscan in use \(em see
\fBamanda-taperscan\fR(7))\&.
.PP
As a precaution,
\fBamlabel\fR
will not write a label if the volume already contains an active label or if the label specified is on an active tape\&. The
[\-f]
(force) flag bypasses these verifications\&.
.SH "OPTIONS"
.PP
\fB\-\-barcode \fR\fB\fIbarcode\fR\fR
.RS 4
With
[\-\-assign], assign the barcode to the label\&. Without
[\-\-assign], label the volume with that barcode\&.
.RE
.PP
\fB\-\-meta \fR\fB\fImeta\-label\fR\fR
.RS 4
Assign the meta label to the label after labeling the volume\&.
.RE
.PP
\fB\-\-assign\fR
.RS 4
Assign the barcode or meta\-label to the label without labeling the volume\&. The label must already be in the tapelist file\&.
.RE
.PP
\fB\-f\fR
.RS 4
Force the label operation; see above
.RE
.PP
\fB\-\-version\fR
.RS 4
Output version information
.RE
.PP
\fB\-o \fR\fB\fIconfigoption\fR\fR
.RS 4
See the "CONFIGURATION OVERRIDE" section in
\fBamanda\fR(8)\&.
.RE
.SH "EXAMPLE"
.PP
Write an Amanda label with the string "DMP000" on the current volume:
.nf
% amlabel daily DMP000 
.fi
.PP
Label the tape in slot 3 of the changer with the label "DMP003":
.nf
% amlabel daily DMP003 slot 3 
.fi
.SH "MESSAGES"
.PP
Label \*(Aq\fIlabel\fR\*(Aq doesn\*(Aqt match labelstr \*(Aq\fIlabelstr\fR\*(Aq
.RS 4
The given label does not match the configured labelstr\&. Even with
\fB\-f\fR, this is an error\&.
.RE
.PP
Label \*(Aq\fIlabel\fR\*(Aq already on a volume
.RS 4
The given label is already on another volume in the tapelist, and Amanda will not write it to this volume unless forced\&.
.RE
.PP
Found label \*(Aq\fIlabel\fR\*(Aq, but it is not from configuration \fIconfig\fR\&.
.RS 4
The label
\fBamlabel\fR
found on the volume does not match this configuration\*(Aqs
\fBlabelstr\fR, so it is probably part of a different Amanda configuration\&. Amanda will not overwrite the label unless it is forced\&.
.RE
.PP
Volume with label \*(Aq\fIlabel\fR\*(Aq contains data from this configuration\&.
.RS 4
The label
\fBamlabel\fR
found on the volume still has valid data on it and Amanda will not overwrite it unless forced\&. Note that this does not distinguish between active and inactive volumes\&.
.RE
.PP
.RS 4
.RE
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBtapelist\fR(5),
\fBamanda-taperscan\fR(7),
\fBamdump\fR(8),
\fBamflush\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
.PP
\fBDustin J\&. Mitchell\fR <\&dustin@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
