'\" t
.\"     Title: amoverview
.\"    Author: Stefan G. Weichinger <sgw@amanda.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMOVERVIEW" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amoverview \- display file systems processed by Amanda over time
.SH "SYNOPSIS"
.HP \w'\fBamoverview\fR\ 'u
\fBamoverview\fR [\-\-hostwidth\ \fIwidth\fR] [\-\-diskwidth\ \fIwidth\fR] [\-\-skipmissed] [\-\-last] [\-\-num0] [\-\-togo0] [\-\-verbose] [\-\-config\ ]\ \fIconfig\fR 
.SH "DESCRIPTION"
.PP
\fBAmoverview\fR
displays a chart showing hosts and file systems processed by Amanda along with the backup level performed each day\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about Amanda\&.
.SH "OPTIONS"
.PP
\fB\-\-config\fR \fIconfig\fR
.RS 4
Use configuration
\fIconfig\fR\&.
.RE
.PP
\fB\-\-hostwidth\fR \fIwidth\fR
.RS 4
Set
\fBhost\fR
field column width to
\fIwidth\fR
characters instead of 8\&.
.RE
.PP
\fB\-\-diskwidth\fR \fIwidth\fR
.RS 4
Set
\fBdisk\fR
field column width to
\fIwidth\fR
characters instead of 20\&.
.RE
.PP
\fB\-\-skipmissed\fR
.RS 4
Compacts the output by only printing stats for the days Amanda actually ran\&.
.RE
.PP
\fB\-\-last\fR
.RS 4
Outputs the last status of each disk at the start\&. Useful for long tapecycles and/or sparse reports\&.
.RE
.PP
\fB\-\-num0\fR
.RS 4
Outputs the number of level 0 dumps for each disk\&.
.RE
.PP
\fB\-\-togo0\fR
.RS 4
Outputs the number of runs until the last level 0 dump is overwritten\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
\fBAmoverview\fR
can take a long while on large systems\&. This option reports intermediate steps while it is working\&.
.RE
.SH "RESULTS"
.PP
\fBamoverview\fR
is a summary of the output of "
\fBamadmin <config> find\fR
"\&. When the last column of
\fBamadmin find\fR
contains anything other than "OK", amoverview translates this into "E" for that day\&.
.PP
A number indicates the level of backup and it succeeded\&. An "E" indicates an error for that day\&. You get an "E" for all errors, like failed to connect, datatimeout, computer crashed, etc, but also for failing to write to tape\&.
.PP
You can have an "E" followed by a number if a filesystem ran into end\-of\-tape once (gives an "E", and later that day, you flush it to a second tape (a number: the level, indicating success)\&. If the flush failed too, you get a double "EE" for that day\&.
.PP
You can also have a double code if you have two tapes in the changer and Amanda failed to write to tape the first time because it hit end of tape (resulting in "E0", for a full, "E1" for an incremental etc\&.) or twice with error ("EE"), and may a successful flush afterwards giving maybe "EE0"\&. (Only the latest 2 characters are printed)\&.
.SH "EXAMPLE"
.PP
This shows the
/home
file system on
\fIhost2\fR
was backed up at level 3 on the 8th, 9th and 10th of December, had a full backup on the 11th, a level 1 on the 12th and a level 2 on the 13th\&.
.nf
# amoverview
                         date 12 12 12 12 12 12
host     disk                 08 09 10 11 12 13
 
host1    /                     0  1  1  1  1  1
host1    /var                  0  1  1  1  1  1
host2    /                     1  1  1  1  1  0
host2    /home                 3  3  3  0  1  2
host2    /opt                  1  1  1  1  1  1
host2    /var                  1  1  0  1  1  1 
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamadmin\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
