'\" t
.\"     Title: amserverconfig
.\"    Author: Kevin Till <kevin.till@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMSERVERCONFIG" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amserverconfig \- program to setup initial Amanda configuration
.SH "SYNOPSIS"
.HP \w'\fBamserverconfig\fR\ 'u
\fBamserverconfig\fR \fIconfig\fR [\-\-template\ \fItemplate\fR] [\-\-no\-vtape] [\-\-tapetype\ \fItapetype\fR] [\-\-tpchanger\ \fItpchanger\fR] [\-\-tapedev\ \fItapedev\fR] [\-\-changerfile\ \fIchangerfile\fR] [\-\-changerdev\ \fIchangerdev\fR] [\-\-labelstr\ \fIlabelstr\fR] [\-\-mailto\ \fImailto\fR] [\-\-dumpcycle\ \fIdumpcycle\fR] [\-\-runspercycle\ \fIrunspercycle\fR] [\-\-runtapes\ \fIruntapes\fR] [\-\-tapecycle\ \fItapecycle\fR] [\-\-help]
.SH "DESCRIPTION"
.PP
After Amanda rpms are successfully installed,
\fBamserverconfig\fR
will setup initial Amanda configuration files\&. It will create /var/lib/amanda/guntar\-lists directory if one does not exist\&.
\fBamserverconfig\fR
does not change existing Amanda configurations\&.
\fBamserverconfig\fR
must be run by user amandabackup\&.
.SH "OPTIONS"
.PP
Options may be abbreviated, as long as the abbreviation is not ambiguous\&. Option argument can either separated by \*(Aq=\*(Aq or a space\&. Example: \-\-templ=harddisk \-\-tapedev /dev/nst0
.PP

\fBamserverconfig\fR
builds a new "config" Amanda configuration\&. Customize the configuration with the options below\&.
.PP
\fB\-\-template template\fR
.RS 4
build Amanda configuration with pre\-configured template files\&. Currently,
\fBharddisk\fR,
\fBsingle\-tape\fR,
\fBtape\-changer\fR
and
\fBS3\fR
are the valid inputs for this option\&. Pre\-configured template files can be found in /var/lib/amanda/template\&.d\&. This option may be combined with other options\&.
.sp
If tape\-changer is chosen for this option, program mtx is required\&.
\fBamserverconfig\fR
will search for mtx in the following directory: "/usr/sbin", "/usr/local/sbin", "/usr/local/bin", "/usr/bin", "/bin" and amandabackup\*(Aqs PATH\&.
.sp
If harddisk is chosen and \-\-no\-vtape is not specified,
\fBamserverconfig\fR
will create and label virtual tape file://var/lib/amanda/vtapes/$config\&.
.RE
.PP
\fB\-\-no\-vtape\fR
.RS 4
Do not create virtual tapes in the harddisk template case\&.
.RE
.PP
\fB\-\-tapedev tapedev\fR
.RS 4
The path name of non\-rewinding tape device\&. default [file://var/lib/amanda/vtapes/$config]
.RE
.PP
\fB\-\-tpchanger tpchanger\fR
.RS 4
The name of the tape changer\&. default [chg\-disk]
.RE
.PP
\fB\-\-changerdev changerdev\fR
.RS 4
A tape changer configuration parameter\&. default [/dev/null]
.RE
.PP
\fB\-\-changerfile changerfile\fR
.RS 4
A tape changer configuration parameter\&. default [/etc/amanda/$config/changer\&.conf]
.RE
.PP
\fB\-\-labelstr labelstr\fR
.RS 4
The tape label constraint regular expression\&. default [^$config\-[0\-9][0\-9]*$]
.sp
If this option is used with \-\-template=harddisk, only alphanumeric string is supported\&.
.RE
.PP
\fB\-\-tapetype tapetype\fR
.RS 4
The type of tape drive associated with tapedev or tpchanger\&. default [HARDDISK]
.RE
.PP
\fB\-\-mailto mailto\fR
.RS 4
A space separated list of recipients for mail reports\&. default [amandabackup]
.RE
.PP
\fB\-\-dumpcycle dumpcycle\fR
.RS 4
The number of days in the backup cycle\&. default [1week]
.RE
.PP
\fB\-\-runspercycle runspercycle\fR
.RS 4
The number of days in the backup cycle\&. default [5]
.RE
.PP
\fB\-\-runtapes runtapes\fR
.RS 4
The maximum number of tapes used in a single run\&. default [1]
.RE
.PP
\fB\-\-tapecycle tapecycle\fR
.RS 4
The size of tape rotation\&. default [25]
.RE
.PP
\fB\-\-help\fR
.RS 4
Display usage\&.
.RE
.SH "FILES"
.PP
\fB/var/lib/amanda/template\&.d\fR
.RS 4
Amanda configuration template files install location
.RE
.PP
\fB/var/lib/amanda\fR
.RS 4
amandabackup home directory
.RE
.PP
\fB/var/lib/amanda/gnutar\-lists\fR
.RS 4
A directory which contains backup timestamp and list of files backed up\&.
.RE
.PP
\fB/etc/amanda/$config\fR
.RS 4
Amanda configuration files location for $config(e\&.g: DailySet1)\&.
.RE
.PP
\fB/etc/amanda/template\&.d\fR
.RS 4
A directory contains dumptypes and tapetypes files used by all Amanda configurations\&.
.RE
.PP
\fB/etc/amandates\fR
.RS 4
Amanda file on the client\&. It keeps track of structures of previous dumps\&.
.RE
.PP
\fB/tmp/amanda\fR
.RS 4
directory contains Amanda debug log files\&.
.RE
.SH "RETURN VALUE"

On success, zero is returned\&.  On error, 1 is returned\&.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBamaddclient\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBKevin Till\fR <\&kevin\&.till@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
