'\" t
.\"     Title: amtapetype
.\"    Author: Dustin J. Mitchell <dustin@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMTAPETYPE" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amtapetype \- generate a tapetype definition by testing the device directly
.SH "SYNOPSIS"
.HP \w'\fBamtapetype\fR\ 'u
\fBamtapetype\fR [\-h] [\-c] [\-f] [\-p] [\-b\ \fIblocksize\fR] [\-t\ \fItypename\fR] [\-l\ \fIlabel\fR] [\fB\-o\fR\ \fIconfigoption\fR...] [\fIconfig\fR] [\fIdevice\fR]
.SH "DESCRIPTION"
.PP
\fBamtapetype\fR
generates a tapetype entry for Amanda by testing the device directly\&.
.SH "OPTIONS"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The options for
\fBamtapetype\fR
have changed in version 2\&.6\&.1
.sp .5v
.RE
.PP
\fB\-h\fR
.RS 4
Display the help message\&.
.RE
.PP
\fB\-c\fR
.RS 4
Run only the hardware compression detection heuristic test and stop\&. This takes a few minutes only\&.
.RE
.PP
\fB\-f\fR
.RS 4
Run amtapetype even if the loaded volume is already labeled\&.
.RE
.PP
\fB\-p\fR
.RS 4
Run only the device property discovery\&.
.RE
.PP
\fB\-b\fR\fI blocksize\fR
.RS 4
block size to use with the device (default: 32k)
.RE
.PP
\fB\-t\fR \fItypename\fR
.RS 4
Name to give to the new tapetype definition\&.
.RE
.PP
\fB\-l\fR\fI label\fR
.RS 4
Label to write on the tape (default is randomly generated)\&.
.RE
.PP
\fB\-o \fR\fB\fIconfigoption\fR\fR
.RS 4
See the "CONFIGURATION OVERRIDE" section in
\fBamanda\fR(8)\&.
.RE
.PP
If a configuration is specified, it is loaded and used to configure the device\&. Note that global configuration parameters are not applied to the device, so if you need to apply properties to a device to run amtapetype, you should supply those properties in a named
\fIdevice\fR
section\&.
.SH "EXAMPLE"
.PP
Generate a tapetype definition for your tape device:
.sp
.if n \{\
.RS 4
.\}
.nf
% amtapetype \-f /dev/nst0
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.PP
If the device cannot reliably report its comprssion status (and as of this writing, no devices can do so), hardware compression is detected by measuring the writing speed difference of the tape drive when writing an amount of compressable and uncompresseable data\&. If your tape drive has very large buffers or is very fast, the program could fail to detect hardware compression status reliably\&.
.PP
Volume capacity is determined by writing one large file until an error, interpereted as end\-of\-tape, is encountered\&. In the next phase, about 100 files are written to fill the tape\&. This second phase will write less data, because each filemark consumes some tape\&. With a little arithmetic,
\fBamtapetype\fR
calculates the size of these filemarks\&.
.PP
All sorts of things might happen to cause the amount of data written to vary enough to generate a strange file mark size guess\&. A little more "shoe shining" because of the additional file marks (and flushes), dirt left on the heads from the first pass of a brand new tape, the temperature/humidity changed during the multi\-hour run, a different amount of data was written after the last file mark before EOT was reported, etc\&.
.PP
Note that the file mark size might really be zero for whatever device this is, and it was just the measured capacity variation that caused
\fBamtapetype\fR
to think those extra file marks in pass 2 actually took up space\&.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda.conf\fR(5)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBDustin J\&. Mitchell\fR <\&dustin@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
.PP
\fBJean\-Louis Martineau\fR <\&martineau@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
