'\" t
.\"     Title: amtoc
.\"    Author: Nicolas Mayencourt <Nicolas.Mayencourt@cui.unige.ch>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMTOC" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amtoc \- generate TOC (Table Of Contents) for an Amanda run
.SH "SYNOPSIS"
.HP \w'\fBamtoc\fR\ 'u
\fBamtoc\fR [\-a] [\-i] [\-t] [\-f\ \fIfile\fR] [\-s\ \fIsubs\fR] [\-w] [\-\-] \fIlogfile\fR
.SH "DESCRIPTION"
.PP
\fIAmtoc\fR
generates a table of contents for an Amanda run\&. It\*(Aqs a perl script (if you don\*(Aqt have perl, install it first!)\&.
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
The output file name will be
\fIlabel\-of\-the\-tape\fR\&.toc in the same directory as
\fIlogfile\fR\&.
.RE
.PP
\fB\-i\fR
.RS 4
Display help about
\fBamtoc\fR\&.
.RE
.PP
\fB\-t\fR
.RS 4
Generate the output in tabular form\&.
.RE
.PP
\fB\-f file\fR
.RS 4
Write the output to a file (\*(Aq\-\*(Aq for stdout)\&.
.RE
.PP
\fB\-s subs\fR
.RS 4
Evaluate the output file name from
\fIsubs\fR, with $_ set to
\fIlabel\-of\-the\-tape\fR\&. The
\fB\-a\fR
option is equivalent to
\fB\-s\fR
\fI\*(Aqs/$_/\&.toc/\*(Aq\fR\&.
.RE
.PP
\fB\-w\fR
.RS 4
Separate tapes with form\-feeds and display blank lines before totals\&.
.RE
.PP
\fB\-\-\fR
.RS 4
Marks the last option so the next parameter is the
\fIlogfile\fR\&.
.RE
.PP
\fBlogfile\fR
.RS 4
(use \*(Aq\-\*(Aq for stdin)
.RE
.SH "OUTPUT FORMAT"
.PP
The standard output has five fields separated by two spaces:
.nf
#  Server:/partition  date  level  size[Kb]
0  daily\-05:  19991005  \-  \-
1  cuisun15:/cuisun15/home  19991005  1  96
2  cuinfs:/export/dentiste  19991005  1  96
  \&.\&.\&.
103  cuisg11:/  19991005  0  4139136
103  total:  \-  \-  16716288
.fi
.PP
In tabular format (\-t), this would look like:
.nf
  #  Server:/partition           date      lev  size[Kb]
  0  daily\-05:                   19991005    \-         \-
  1  cuisun15:/cuisun15/home     19991005    1        96
  2  cuinfs:/export/dentiste     19991005    1        96
  \&.\&.\&.
103  cuisg11:/                   19991005    0   4139136
103  total:                      \-           \-  16716288
.fi
.SH "USAGE"
.PP
The easiest way to use it is to run
\fBamtoc\fR
right after
\fIamdump\fR
in the
\fIcron job:\fR
.nf
amdump daily ; logdir=`amgetconf daily logdir` ; log=`ls \-1t $logdir/log\&.*\&.[0\-9] | head \-1` ; amtoc \-a $log
.fi
.PP
which will generate /usr/local/etc/amanda//daily/\fItape_label\fR\&.toc\&. You may also want to call
\fBamtoc\fR
after an
\fIamflush\fR\&.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamdump\fR(8),
\fBamflush\fR(8),
\fBamgetconf\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHORS"
.PP
\fBNicolas Mayencourt\fR <\&Nicolas\&.Mayencourt@cui\&.unige\&.ch\&>
.RS 4
University of Geneva/Switzerland
.RE
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
