'\" t
.\"     Title: amvault
.\"    Author: Dustin J. Mitchell <dustin@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 02/21/2012
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.3.1
.\"  Language: English
.\"
.TH "AMVAULT" "8" "02/21/2012" "Amanda 3\&.3\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amvault \- Copy Amanda dumps from one volume to another
.SH "SYNOPSIS"
.HP \w'\fBamvault\fR\ 'u
\fBamvault\fR [\fB\-o\fR\ \fIconfigoption\fR...] [\-\-dry\-run | \-n] [\-\-quiet | \-q] [\-\-fulls\-only] [\-\-export] [\fB\-\-src\-timestamp\fR\ \fIsrc\-timestamp\fR]
.br
\fB\-\-label\-template\fR\ \fIlabel\-template\fR \fB\-\-dst\-changer\fR\ \fIdst\-changer\fR [\fB\-\-autolabel\fR\ \fIautolabel\-arg\fR...]
.br
\fIconfig\fR [\fIhostname\fR\ [\ \fIdisk\fR\ [\ \fIdate\fR\ [\ \fIlevel\fR\ [\ \fIhostname\fR\ [\&.\&.\&.]\ ]\ ]\ ]\ ]]
.SH "WARNING"
.PP
This application is not yet in its final form, and is subject to major revision in subsequent versions of Amanda\&. Backward compatibility is not guaranteed\&.
.PP
Note that Amanda restore/recover operations will request tertiary media by label when dumpfiles are not found on secondary media, but there is no provision to automatically fetch such media from a different changer
.PP
Feedback on and patches to this application are invited and encouraged!
.SH "DESCRIPTION"
.PP
Amvault is conceptually equivalent to "amfetchdump | taper"\&. That is, it reads specified dumps from secondary media and re\-writes them on tertiary media\&.
.PP
\fBAmvault\fR
Copies data from the run with timestamp
\fBsrc\-timestamp\fR
onto volumes using the changer
\fBdst\-changer\fR, and labeling new volumes with
\fBlabel\-template\fR\&.
.SS "Secondary Media"
.PP
The dumps to be read from secondary media can be specified by any combination of dump specifications,
\fB\-\-fulls\-only\fR, and
\fB\-\-src\-timestamp\fR\&. At least one must be specified, lest amvault attempt to vault all dumps in the catalog\&. See
\fBamanda-match\fR(7)
for more information on dump specifications\&.
.PP
Note that the datestamp given in the dumpspec is the
\fIdump\fR
datestamp \- the run in which the backup was taken on the Amanda client\&. The
\fB\-\-src\-timestamp\fR, on the other hand, is the
\fIwrite\fR
timestamp \- the run in which the dump was written to secondary media\&. The latter option facilitates duplicating the results of an entire backup run, including any dumps that might have been flushed from holding disk\&.
.SS "Tertiary Media"
.PP
The
\fB\-\-dst\-changer\fR
must be specified, and names the changer in which tertiary media are stored\&.
.PP
If
\fBamanda.conf\fR(5)
contains the new
\fBpart\-size\fR
splitting parameters, then amvault will use them without any additional configuration\&. However, if the configuration still uses the old splitting parameters (\fBtape_splitsize\fR,
\fBsplit_diskbuffer\fR, and
\fBfallback_splitsize\fR), then amvault will need some additional configuration in order to properly split dumps to tertiary media\&. To do so, specify a new tapetype in
\fBamanda.conf\fR(5), say "TERTIARY", and set the
\fBpart\-size\fR
and other appropriate parameters there\&. Then reference that tapetype in the amvault invocation:
.sp
.nf
    amvault \-otapetype=TERTIARY \&.\&.\&.
.fi
.SH "OPTIONS"
.PP
\fB\-\-autolabel\fR [any] [other\-config] [non\-amanda] [volume\-error] [empty]
.RS 4
Works just like the
\fBautolabel\fR
parameter in
\fBamanda.conf\fR(5), and can be specified multiple times if necessary\&. The default is \*(Aqempty\*(Aq\&.
.RE
.PP
\fB\-\-dst\-changer\fR \fIdst\-changer\fR
.RS 4
Specifies the changer in which tertiary media are stored\&. In general, this should be different from the secondary changer, to eliminate the possibility of overwriting secondary media with tertiary data\&.
.sp
The
\fBdst\-changer\fR
parameter should specify the name of a changer defined in
\fBamanda.conf\fR(5)\&. For example:
.sp
.nf
define changer vaulting_tape {
    tapedev "/dev/rmt/1n"
    tpchanger "chg\-zd\-mtx"
    changerdev "/dev/sg0"
    changerfile "vaulting\-changer\&.conf"
}
.fi
.RE
.PP
\fB\-\-dry\-run\fR, \fB\-n\fR
.RS 4
Cause amvault to print the dumps it would vault, but not actually perform any vaulting operations\&.
.RE
.PP
\fB\-\-export\fR
.RS 4
Cause amvault to attempt to move completed tertiary volumes to import/export slots, where they can be more easily removed by an operator\&.
.RE
.PP
\fB\-\-\-fulls\-only\fR
.RS 4
Only full (level\-0) dumps are copied\&.
.RE
.PP
\fB\-\-label\-template\fR \fIlabel\-template\fR
.RS 4
Specifies a label template which is used to generate new labels for tertiary volumes\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Eliminate non\-error messages, and is useful when running amvault from cron\&.
.RE
.PP
\fB\-\-src\-timestamps\fR \fIsrc\-timestamps\fR
.RS 4
Specifies the timestamps in the format \*(AqYYYYMMDDHHMMSS\*(Aq of the run to vault, can be "latest", then the most recent amdump or amflush run will be used\&.
.RE
.PP
\fB\-o\fR \fIconfigoption\fR
.RS 4
See the "\fBCONFIGURATION OVERRIDE\fR" section in
\fBamanda\fR(8)\&.
.RE
.SH "EXAMPLES"
.PP
Vault all dump written to tape in the latest amdump or amflush run:
.nf
$ amvault \-\-src\-timestamps latest \-\-label\-template "CONF\-%%%" \-\-dst\-changer vault\-changer CONF
.fi
.PP
Vault all dump written on the run of December 7 2011 12:13:14 :
.nf
$ amvault \-\-src\-timestamps 20111207121314 \-\-label\-template "CONF\-%%%" \-\-dst\-changer vault\-changer CONF
.fi
.PP
Vault all dump dumped on any run of December 7 2011:
.nf
$ amvault \-\-label\-template "CONF\-%%%" \-\-dst\-changer vault\-changer CONF \e* \e* 20111207
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda-changers\fR(7),
\fBamfetchdump\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBDustin J\&. Mitchell\fR <\&dustin@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (http://www\&.zmanda\&.com)
.RE
